version: "3"
services:
        pockemon_world:
                build: .
                ports:
                - 8000:8000
                healthcheck:
                        test: ["CMD-SHELL", "curl localhost:8000/healthcheck/ | grep Ok"]
                        interval: 5s
                        timeout: 1s
                        retries: 2
                network_mode: "host"
