version: "3"
services:
  concierge:
    build: .
    ports:
      - 8000:8000
    healthcheck:
      test: ["CMD-SHELL", "curl localhost:8000/healthcheck/ | grep OK"]
      interval: 10s
      timeout: 1s
      retries: 2

  database:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=concierge
      - PG_DATA=/var/lib/postgresql/data
    ports:
      - 5433:3433
    volumes:
      - ./data:/var/lib/postgresql
